version: '3.4'

services:
  lilartist.community.pl.webapilinux:
    image: lilartistcommunityplwebapilinux:dev
    container_name: LilArtist.Community.PL.WebApiLinux
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "LilArtist.Community.PL.WebApiLinux"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages
    volumes:
      - C:\Users\betme\OneDrive\Документы\GitHub\LilArtist.Community\LilArtist.Community\LilArtist.Community.PL.WebApiLinux:/app
      - C:\Users\betme\OneDrive\Документы\GitHub\LilArtist.Community\LilArtist.Community:/src
      - C:\Users\betme\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\betme\.nuget\packages\:/root/.nuget/packages:ro
      - C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages:/root/.nuget/fallbackpackages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  \"/app/bin/Debug/net6.0/LilArtist.Community.PL.WebApiLinux.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true